### ISSUE TITLE
No more PHP 7.1 support

### ISSUE THREAD

**Issue by kukulich** [slevomat/coding-standard#1082]

**Comment by dereuromark** [comment]
7.3+ sounds reasonable for the time being
if possible, also 7.2 is OK, if no 7.3+ things are being used there is no need to restrict higher than necessary.

**Comment by mabar** [comment]
Do you plan to drop support of php 7.1 completely or just increase requirements for library instalation?
Imho dev tools could support running on latest php only while still being able to analyse older php versions based code. e.g. run only on php 8+ so you can upgrade your codebase and oficially support analysis of php 5.3 codebases.
We just have to find an easy way to install the tool - phar + automatic php features downgrade (via rector) or separate installation from main composer.json (because php version constraint would be too restrictive)

**Comment by kukulich** [comment]
@mabar Probably both.

**Comment by kukulich** [comment]
https://github.com/slevomat/coding-standard/commit/2dcda0735e62ae65b9e2ff22c8514883042d1c95
