### ISSUE TITLE
Notices are thrown because T_RETURN_TYPE is missing

### ISSUE THREAD

**Issue by fabik** [slevomat/coding-standard#18]
Commit cf2387121e97f64c72721ac0722618d70b24a20c causes phpcs to throw notices:

```
PHP Notice: Use of undefined constant T_RETURN_TYPE - assumed 'T_RETURN_TYPE' in /home/ubuntu/example/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/ReferencedNameHelper.php on line 121
```

**Comment by ondrejmirtes** [comment]
What method of installation do you use? Are you sure you have correct version of PHPCS installed?

Because `T_RETURN_TYPE` constant is [defined as part of PHP_CodeSniffer itself](https://github.com/squizlabs/PHP_CodeSniffer/blob/b062aefede08b15b6691e6e24bf9befad80e49cb/CodeSniffer/Tokens.php#L75), so I don't know how it could not be defined under PHP 5.6.

**Comment by fabik** [comment]
I've installed phpcs using Composer by adding
```
"require-dev": {
	"slevomat/coding-standard": "^1.0",
	"consistence/coding-standard": "^0.8"
}
```
to composer.json.

According to vendor/composer/installed.json Composer installed package squizlabs/php_codesniffer in version 2.3.4.

**Comment by fabik** [comment]
Constant T_RETURN_TYPE has been added to phpcs in version 2.4.0.
https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/2.4.0

I'd suggest adding
```
"require": {
	"squizlabs/php_codesniffer": "^2.4"
}
```
to composer.json of this library.

**Comment by fabik** [comment]
I solved the problem by updating consistence/coding-standard to 0.10.1.

Thank you for help!
