### ISSUE TITLE
Making LongTypeHints fixable

### ISSUE THREAD

**Issue by Majkl578** [slevomat/coding-standard#237]
I'd love to see a fixer for this sniff. I've been recently converting some code with long type names and fixing all of these manually becomes really tedious very soon. 😖 

Should be trivial to implement, could PR later.

**Comment by kukulich** [comment]
I thought it was not so easy to implement fixability when I created the sniff and it was easy to do global search&replace via PHPStorm that's why I didn't implement it for the first time.

However I had easy idea today how to do it so it is done :) https://github.com/slevomat/coding-standard/commit/accf5e3e049327bf43f0782caeced520217f2a8b
