### ISSUE TITLE
EarlyExitSniff throws exception for "else if"

### ISSUE THREAD

**Issue by Majkl578** [slevomat/coding-standard#365]
Using `else if` instead of `elseif` makes the sniff throw an exception:
```
Fatal error: Uncaught Exception: "else" without curly braces is not supported. 
```

```php
} else if (...) {
```

This should imho be interpreted the same way as `elseif`.

**Comment by kukulich** [comment]
If somebody prepares PR, I’m ok to merge it but I don’t want to invest my time to support it :)

**Comment by jrfnl** [comment]
Just ran into this as well.

Looks like this issue exists in all of the following classes:
* `ControlStructures\AbstractControlStructureSpacingSniff`
* `ControlStructures\EarlyExitSniff`
* `ControlStructures\RequireTernaryOperatorSniff`
* `ControlStructures\UselessIfConditionWithReturnSniff`

The biggest problem with this is that it breaks the rest of the PHPCS run because of the uncaught exception. (PHPCS will stop scanning the file completely at an uncaught exception)

If you don't want to handle that situation, that's fine, but use an `return` instead of an exception in that case.
