### ISSUE TITLE
Declare Compatibility with PHP 8

### ISSUE THREAD

**Issue by XedinUnknown** [slevomat/coding-standard#679]
When building on a CI server, builds on PHP nightly fail. That's because the current nightly is PHP 8, and this package does not declare compatibility with it.

Unless you think there is a reason it is incompatible, could you kindly declare compatibility? If actual incompatibilities are found in the future, you can always remove it. Nobody is going to get angry, since this is alpha stuff.

**Comment by ondrejmirtes** [comment]
Hi, we discussed this with @kukulich and this request does not make much sense to us.

1) We cannot declare compatibility with PHP 8 because we don't know how it will look like and what the BC breaks are.
2) You should not run PHP_CodeSniffer (and this package) on unsupported versions. There might be reasons for why you're running your CI build on PHP nightly, but that's probably for testing your own application. The result of PHPCS should stay the same across different PHP versions so it's sufficient to run it only once on a supported PHP version, like PHP 7.3.

**Comment by XedinUnknown** [comment]
Hi! Thanks for the response. I guess I should have clarified that the problem is not with _running_ PHPCS with this standard, but with _installing_ the standard with Composer.

On one hand, you can't declare compatibility with something you don't know about, because there may be things that break. On the other hand, however, nothing might break, so it could make sense to declare it compatible _until_ problems are found.

Again, this is only for the sake of installing the package.

Please reconsider.

**Comment by ondrejmirtes** [comment]
You should install dependencies on PHP 8 with `--ignore-platform-reqs`.

**Comment by XedinUnknown** [comment]
Seems like a way. Will try that, thanks!
