### ISSUE TITLE
Type information is not inherited

### ISSUE THREAD

**Issue by greg0ire** [slevomat/coding-standard#991]
The following code produces an error:
```php
<?php
asbtract class AbstractPlatform
{
    /**
     * @param string $database
     *
     * @return string
     *
     * @throws DBALException If not supported on this platform.
     */
    public function getListSequencesSQL($database)
    {
        throw DBALException::notSupported(__METHOD__);
    }
}

class PostgreSqlPlatform extends AbstractPlatform
{
    public function getListSequencesSQL($database)
    {
        return "SELECT sequence_name AS relname,
                       sequence_schema AS schemaname
                FROM   information_schema.sequences
                WHERE  sequence_schema NOT LIKE 'pg\_%'
                AND    sequence_schema != 'information_schema'";
    }
}
```

Here are the errors I get:

```
 243 | ERROR | Method \Doctrine\DBAL\Platforms\PostgreSqlPlatform::getListSequencesSQL() does not have parameter type hint nor @param annotation for its parameter $database.
     |       | (SlevomatCodingStandard.TypeHints.ParameterTypeHint.MissingAnyTypeHint)
 243 | ERROR | Method \Doctrine\DBAL\Platforms\PostgreSqlPlatform::getListSequencesSQL() does not have return type hint nor @return annotation for its return value.
     |       | (SlevomatCodingStandard.TypeHints.ReturnTypeHint.MissingAnyTypeHint)
```

`{@inheritDoc}` is enough to make the issue go away, but as pointed out by @morozov in https://github.com/doctrine/dbal/pull/3983#discussion_r418987426 , it should not be necessary, as per [the phpdoc docs](https://docs.phpdoc.org/latest/guides/inheritance.html#the-inheritdoc-tag): 

> Currently some applications have DocBlocks containing just the `{@inheritDoc}` inline tag to indicate that their complete contents should be inherited. This usage breaks with the PHPDoc Standard as summaries cannot contain inline tags and inheritance is automatic; you do not need to define a special tag for it.

**Comment by kukulich** [comment]
PHPCS works in one-line scope so it does not know anything about parents.

**Comment by morozov** [comment]
@kukulich it's clear why it happens but it doesn't mean that the issue doesn't exist.

The coding standard takes the responsibility of using phpDocs to validate the method signature but does not follow the phpDoc standard.

Thereby, it (essentially) forces (due to its technical limitations) its users to abuse the standard to be compliant with the coding standard. Essentially, the coding standard contradicts phpDoc which it's based on.

**Comment by kukulich** [comment]
> it (essentially) forces (due to its technical limitations) its users to abuse the phpDoc standard

It's not true. You are not forced to abuse the phpDoc standard. You can copy the documentation - yes, it's not optimal (because of technical limitations) but it is valid.

Btw I think that `@inheritDoc` works as well:

```
However, it does make clear that an element has been explicitly documented (and thus not forgotten). As such we are working to include a new (normal) tag in the PHPDoc Standard @inheritDoc that will serve that purpose.
```

**Comment by morozov** [comment]
> It's not true. You are not forced to abuse the phpDoc standard. You can copy the documentation - yes, it's not optimal (because of technical limitations) but it is valid.

I agree. “Forces” was an overstatement. @greg0ire would it make sense to do that instead of using `{@inheritDoc}`?

@kukulich, would it make sense to add an option that would tell the standard to ignore the missing `@param`, `@return` and other similar annotations if the class extends another one or implements an interface where those annotations _may_ be defined?

This way, it could be enabled by default but it could be turned on manually to double-check if the missing annotations are really inherited. I.e. there would be a way to stay compliant with phpDoc w/o copy/pasting type definitions and w/o suppressing the coding standard using `{@inheritDoc}`.

**Comment by greg0ire** [comment]
> I agree. “Forces” was an overstatement. @greg0ire would it make sense to do that instead of using {@inheritDoc}?

Not much. I'd rather migrate to just `@inheritDoc`, which seems more appropriate and less repetitive

**Comment by greg0ire** [comment]
Ah I found an interesting discussion: https://github.com/phpDocumentor/phpDocumentor/issues/2076

@morozov I think we should stick with `{@inheritDoc}` for now.

**Comment by morozov** [comment]
Honestly, I don't see much point in `@inheritDoc` — as documentation, it doesn't add any value.

**Comment by greg0ire** [comment]
> However, it does make clear that an element has been explicitly documented (and thus not forgotten).

No value for the reader indeed. It's just here for the writer, to help them know if they need to check this in case it has been forgotten.

**Comment by kukulich** [comment]
> would it make sense to add an option that would tell the standard to ignore the missing @param, @return and other similar annotations if the class extends another one or implements an interface where those annotations may be defined?

It's possible but I don't think it's a good idea. It's better to document it by `@inheritdoc` or by copy&paste so you know you did not forget to document it.
